myProjDJango/myProjDJango/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage ),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT ) 

myProjDJango/posts/urls.py
from django.urls import path
from .import views

app_name = "posts"

urlpatterns = [
    
    path('', views.posts_list , name="list"),
    path('<slug:slug>', views.post_page , name="page"),
    
]

myProjDJango/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
]

myProjDJango/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    def __str__(self): #
        return self.title
    
   
        

myProjDJango/users/models.py
from django.db import models

# Create your models here.

myProjDJango/myProjDJango/views.py
# from django.http import  HttpResponse
from django.shortcuts import render,redirect

def homepage(request):
    # return HttpResponse("Hello World! I'm Home. ")
    return  render(request,'home.html')

def about(request):
    # return HttpResponse('My About Page.')
    return render (request,"about.html")

# def register(request):
#     # return HttpResponse('My Register Page.')
#     return render (request,"register.html")

myProjDJango/posts/views.py
from django.shortcuts import render
from  .models import Post


# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {"posts": posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {"post": post})

myProjDJango/users/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm 

# Create your views here.
def register_view(request):
    if request.method == "POST": 
        form = UserCreationForm(request.POST) 
        if form.is_valid(): 
            form.save() 
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

myProjDJango/posts/templates/posts/post_page.html
{% extends "layout.html"  %}

{% block title %}
    {{post.title}}
{% endblock %}

{% block content %}
    <section>
        <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}"/>
        <h1>{{post.title}}</h1>
        <p>{{post.body}}</p>
        <p>{{post.date}}</p>

        
    </section>
{% endblock %}

myProjDJango/posts/templates/posts/posts_list.html
{% extends "layout.html"  %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
        <h1>Posts</h1>
        {% for  post in posts %}
            <article class="post">

                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                    {{post.title}}
                    </a>
                </h2>

                <p>{{post.body}}</p>
                <p>{{post.date}}</p>
        {% endfor %}
    </section>
{% endblock %}

myProjDJango/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="{% static  'css/style.css' %}" />
</head>
<body>
    <h1>About</h1>
    <p>Check out my Home Page <a href="/"><button>Here! </button></a></p>
</body>
</html>

myProjDJango/templates/home.html
{% extends "layout.html"  %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my About Page <a href="/about"><button>Here! </button></a></p>
{% endblock %}

myProjDJango/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static  'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/" >
            <span role="img" aria-label="Home">🏠</span>
        </a> | 
        <a href="/about" >
            <span role="img" aria-label="About">😁</span>
        </a> | 
        <a href="{% url 'posts:list' %}" >
            <span role="img" aria-label="Post">📰</span>
        </a> 
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

myProjDJango/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}